### ISSUE TITLE
Missing memory device types

### ISSUE THREAD

**Issue by ldfsilva** [jcreekmore/dmidecode#19]
The [smbios 3.2 spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.2.0.pdf) (ie: page 98) shows two memory device types that are not present in [017_memory_device.rs](https://github.com/jcreekmore/dmidecode/blob/master/src/structures/017_memory_device.rs#L187), they are:

```
LPDDR4
Logical non-volatile device
```

Let me know if that's something you want to tackle or I can put out a PR for this one @jcreekmore .

**Comment by jcreekmore** [comment]
If it is something that you want/need in the near term, go ahead and do a PR. Otherwise, it will probably be a while before I get to it.

**Comment by jcreekmore** [comment]
Closed by #20

**Comment by jcreekmore** [comment]
I will bump the crate in the morning.
