### ISSUE TITLE
smbios 2.8 Formatted section length of structure MemoryDevice with handle 78 should be 40 bytes

### ISSUE THREAD

**Issue by ldfsilva** [jcreekmore/dmidecode#21]
Similarly to issue #17 this time the length enforcement in [017_memory_device](https://github.com/jcreekmore/dmidecode/blob/master/src/structures/017_memory_device.rs#L404-L406) leads to `InvalidFormattedSectionLength` errors on systems running smbios 2.8

The aforementioned enforcement requires a length of 0x28 (40 bytes), whereas the system reports a length of 0x22 (34 bytes), as shown in [1].

[smbios 2.8 spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_2.8.0.pdf) (ie: page 86) states that:

> "Length of the structure, 15h for version 2.1, 1Bh for version 2.3, 1Ch for version 2.6, 22h for version 2.7, **28h for version 2.8 and later**"

Not a conforming spec vs reality =\

@jcreekmore I can put out a fix to use `< 0x22` instead of `!= 0x28` -- let me know your thoughts.

[1] Excerpt from `dmidecode` in smbios 2.8

```
# dmidecode -H 78 -u
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.
54 structures occupying 2217 bytes.
Table at 0x7F4EC000.

Handle 0x004E, DMI type 17, 34 bytes
        Header and Data:
                11 22 4E 00 4C 00 FE FF 40 00 40 00 00 20 09 00
                01 02 18 80 40 40 06 03 04 05 06 02 00 00 00 00
                40 06
```

**Comment by jcreekmore** [comment]
Closed by #22
