### ISSUE TITLE
smbios 2.8 Invalid processor family

### ISSUE THREAD

**Issue by ldfsilva** [jcreekmore/dmidecode#23]
Experiencing crashes in systems with smbios 2.8 and ATOM processors, parsing fails when handling processor family with:

```
Invalid processor family
```

As follows a sample system processor information where it's happening, I'm suspecting it can be related to the parsing of extended [processor_family](https://github.com/jcreekmore/dmidecode/blob/master/src/structures/004_processor.rs#L735) within `packed.processor_family_2` vs `packed.processor_family`. Not confirmed yet.

```
dmidecode -H 0x48 -u
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.
54 structures occupying 2217 bytes.
Table at 0x7F4EC000.

Handle 0x0048, DMI type 4, 42 bytes
        Header and Data:
                04 2A 48 00 01 03 2B 02 D8 06 04 00 FF FB EB BF
                03 90 64 00 28 0A 60 09 41 01 46 00 47 00 FF FF
                00 04 00 08 08 08 04 00 00 00
        Strings:
                43 50 55 30 00
                CPU0
                49 6E 74 65 6C 28 52 29 20 43 6F 72 70 6F 72 61
                74 69 6F 6E 00
                Intel(R) Corporation
                49 6E 74 65 6C 28 52 29 20 41 74 6F 6D 28 54 4D
                29 20 43 50 55 20 20 43 32 37 35 30 20 20 40 20
                32 2E 34 30 47 48 7A 00
                Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
                50 72 6F 63 65 73 73 6F 72 49 6E 66 6F 5F 41 53
                53 45 54 5F 54 41 47 00
                ProcessorInfo_ASSET_TAG
```

**Comment by jcreekmore** [comment]
I suspect that I need to revisit this and go to an approach more like the C program does of walking memory and grabbing the fields if the length is long enough and letting them be None otherwise and not relying on the firmware manufacturers actually following the spec.

**Comment by ldfsilva** [comment]
@jcreekmore check out the proposed fix in the PR. Note that although I haven't faced issues with `ProcessorPacked_3_0`, smbios 2.8+, I suspect that's likely to face similar problem as of now it also forces [processor_family_2](https://github.com/jcreekmore/dmidecode/blob/master/src/structures/004_processor.rs#L763).
