### ISSUE TITLE
Missing memory device types DDR5

### ISSUE THREAD

**Issue by ldfsilva** [jcreekmore/dmidecode#27]
The [smbios 3.4 spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf) (ie: page 104) shows DDR5 memory device types that are not present in [017_memory_device.rs](https://github.com/jcreekmore/dmidecode/blob/master/src/structures/017_memory_device.rs#L187), they are:

- DDR5 
- LPDDR5

I can put out a PR for this @jcreekmore, giving you a heads up.

**Comment by jcreekmore** [comment]
Sounds good

**Comment by jcreekmore** [comment]
Fixed by #28
