### ISSUE TITLE
Release a new version of dmidecode with a LICENSE file

### ISSUE THREAD

**Issue by tmarucci-qumulo** [jcreekmore/dmidecode#38]
In order to use this crate, I need it to include a LICENSE file. I submitted a pull request and got that merged in. Unfortunately, in order to properly download it a new version of the crate would have to be published to crates.io.

I'm happy to help with this, but AFAIK the owner of the crate must be the one to publish it.

**Comment by jcreekmore** [comment]
Released v0.7.7

**Comment by tmarucci-qumulo** [comment]
thank you so much!
